name: Conan

on:
  push:
    branches: [ master ]
  
env:
  BUILD_TYPE: Debug
  CMAKE_PRESET: debug

jobs:
  ubuntu:
    env:
      CONAN_PROFILE: ubuntu-22.04

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      
    - name: Create install profiles
      run: conan config install profiles
      
    - name: Build in one command
      run: conan build . -s build_type=${{env.BUILD_TYPE}} --build=missing -pr ${{env.CONAN_PROFILE}}

    - name: Build with CMake workflow
      run: cmake --workflow --preset ${{env.CMAKE_PRESET}}
