name: Conan

on:
  push:
    branches: [ master ]
  
env:
  BUILD_TYPE: Debug
  CMAKE_PRESET: debug

jobs:
  ubuntu:
    env:
      CONAN_PROFILE: ubuntu-22.04

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1
      
    - name: Build in one command
      run: conan build . -s build_type=${{env.BUILD_TYPE}} --build=missing -pr:b=profiles/${{env.CONAN_PROFILE}} -pr:h=profiles/${{env.CONAN_PROFILE}}

    - name: Build with CMake workflow
      run: cmake --workflow --preset ${{env.CMAKE_PRESET}}
