name: Conan

on:
  push:
    branches: [ master ]
  
env:
  BUILD_TYPE: Debug
  CMAKE_PRESET: debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      
    - name: Create default profile
      run: conan profile detect
      
    - name: Update profile
      run: |
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan profile update settings.compiler.cppstd=20 default
      
    - name: Build in one command
      run: conan build . -s build_type=${{env.BUILD_TYPE}} --build=missing

    - name: Build with CMake workflow
      run: cmake --workflow --preset ${{env.CMAKE_PRESET}}
